import { Injectable } from '@angular/core';
import { Player  } from '../models/player';
import { Team, Roster, RosterSpot } from '../models/team';
import { GeneratePlayerService } from './generate-player.service';
import { LeagueDataService } from './league-data.service';
import 'rxjs/add/operator/toPromise';

@Injectable()
export class GenerateTeamService {
    players = [];
    constructor(private generatePlayerSerivce: GeneratePlayerService,
                private leagueDataService: LeagueDataService) { }

    async generateRandomTeam(leagueId: string) {
      const team = await this.leagueDataService.createTeam(new Team(this.getTeamName(), this.getTeamLocation(),
        new Roster(new Array<RosterSpot>(), new Array<RosterSpot>()), leagueId)) as Team;
      return await this.generateTeam(leagueId, team)
    }

    async generateMlbTeam(leagueId: string, mlbTeamIndex: number) {
      const team = await this.leagueDataService.createTeam(new Team(this.mlbTeamNames[mlbTeamIndex], this.mlbLocations[mlbTeamIndex],
        new Roster(new Array<RosterSpot>(), new Array<RosterSpot>()), leagueId)) as Team;
      return await this.generateTeam(leagueId, team)
    }

    async generateTeam(leagueId: string, team: Team) {
        for (let x = 0; x < 15; x++) {
            const batter = await this.generatePlayerSerivce.generateBatter(leagueId, team._id, (new Date()).getFullYear());
            this.players.push(batter);
            if (x < 9) {
              team.roster.batters.push(new RosterSpot(batter._id, this.positions[x], x + 1));
            } else {
              team.roster.batters.push(new RosterSpot(batter._id, null, null));
            }
        }

        for (let y = 0; y < 10; y++) {
            const pitcher = await this.generatePlayerSerivce.generatePitcher(leagueId, team._id, (new Date()).getFullYear());
            this.players.push(pitcher);
            if (y < 5) {
              team.roster.pitchers.push(new RosterSpot(pitcher._id, this.pitcherRoles[y], null));
            } else {
              team.roster.pitchers.push(new RosterSpot(pitcher._id, null, null));
            }
        }
        const updatedTeam = await this.leagueDataService.updateTeam(team);
        return updatedTeam as Team
    }

    getTeamName() {
        return this.teamNames[Math.round(Math.random() * (this.teamNames.length - 1))];
    }

    getTeamLocation() {
        return this.teamLocations[Math.round(Math.random() * (this.teamLocations.length - 1))];
    }
        // tslint:disable:member-ordering
     pitcherRoles = [
      'SP1',
      'SP2',
      'SP3',
      'SP4',
      'SP5'
    ]

     positions = [
      'C',
      '1B',
      '2B',
      '3B',
      'SS',
      'LF',
      'CF',
      'RF',
      'DH'
    ]

    teamLocations = [
 'Akron',
'Albuquerque',
'Alexandria',
'Amarillo',
'Anaheim',
'Anchorage',
'Arlington',
'Athens',
'Atlanta',
'Augusta',
'Aurora',
'Aurora',
'Austin',
'Bakersfield',
'Baltimore',
'Baton Rouge',
'Bellevue',
'Birmingham',
'Boise',
'Boston',
'Bridgeport',
'Brownsville',
'Buffalo',
'Cape Coral',
'Carrollton',
'Cary',
'Cedar Rapids',
'Chandler',
'Charleston',
'Charlotte',
'Chattanooga',
'Chesapeake',
'Chicago',
'Chula Vista',
'Cincinnati',
'Clarksville',
'Cleveland',
'Colorado Springs',
'Columbia',
'Columbus',
'Concord',
'Coral Springs',
'Corona',
'Corpus Christi',
'Dallas',
'Dayton',
'Denton',
'Denver',
'Des Moines',
'Detroit',
'Durham',
'El Paso',
'Elizabeth',
'Elk Grove',
'Escondido',
'Eugene',
'Fayetteville',
'Fontana',
'Fort Collins',
'Fort Lauderdale',
'Fort Wayne',
'Fort Worth',
'Fremont',
'Fresno',
'Frisco',
'Fullerton',
'Gainesville',
'Garden Grove',
'Garland',
'Gilbert',
'Glendale',
'Glendale',
'Grand Prairie',
'Grand Rapids',
'Greensboro',
'Hampton',
'Hartford',
'Hayward',
'Henderson',
'Hialeah',
'Hollywood',
'Honolulu',
'Houston',
'Huntington Beach',
'Huntsville',
'Indianapolis[11]',
'Irvine',
'Irving',
'Jackson',
'Jacksonville',
'Jersey City',
'Joliet',
'Kansas City',
'Kent',
'Killeen',
'Knoxville',
'Lafayette',
'Lakewood',
'Lancaster',
'Laredo',
'Las Vegas',
'Lexington',
'Lincoln',
'Little Rock',
'Long Beach',
'Los Angeles',
'Louisville',
'Lubbock',
'Macon',
'Madison',
'McAllen',
'McKinney',
'Memphis',
'Mesa',
'Mesquite',
'Miami',
'Midland',
'Milwaukee',
'Minneapolis',
'Miramar',
'Mobile',
'Modesto',
'Montgomery',
'Moreno Valley',
'Murfreesboro',
'Naperville',
'Nashville',
'New Haven',
'New Orleans',
'New York',
'Newark',
'Newport News',
'Norfolk',
'North Las Vegas',
'Oakland',
'Oceanside',
'Oklahoma City',
'Olathe',
'Omaha',
'Ontario',
'Orange',
'Orlando',
'Overland Park',
'Oxnard',
'Palmdale',
'Pasadena',
'Pasadena',
'Paterson',
'Pembroke Pines',
'Peoria',
'Philadelphia',
'Phoenix',
'Pittsburgh',
'Plano',
'Pomona',
'Port St. Lucie',
'Portland',
'Providence',
'Raleigh',
'Rancho Cucamonga',
'Reno',
'Richmond',
'Riverside',
'Rochester',
'Rockford',
'Roseville',
'Sacramento',
'Saint Paul',
'Salem',
'Salinas',
'Salt Lake City',
'San Antonio',
'San Bernardino',
'San Diego',
'San Francisco',
'San Jose',
'Santa Ana',
'Santa Clara',
'Santa Clarita',
'Santa Rosa',
'Savannah',
'Scottsdale',
'Seattle',
'Shreveport',
'Simi Valley',
'Sioux Falls',
'Spokane',
'Springfield',
'Springfield',
'St. Louis',
'St. Petersburg',
'Stamford',
'Sterling Heights',
'Stockton',
'Sunnyvale',
'Surprise',
'Syracuse',
'Tacoma',
'Tallahassee',
'Tampa',
'Tempe',
'Thornton',
'Thousand Oaks',
'Toledo',
'Topeka',
'Torrance',
'Tucson',
'Tulsa',
'Vancouver',
'Virginia Beach',
'Visalia',
'Waco',
'Warren',
'Washington',
'West Valley City',
'Wichita',
'Winston-Salem',
'Worcester',
'Yonkers'
]

teamNames = [
'49ers',
'51s',
'66ers',
'76ers',
'Aces',
'Admirals',
'AirHogs',
'Alouettes',
'Amberjacks',
'Angels',
'AquaSox',
'Argonauts',
'Argyle',
'Arsenal',
'Astros',
'Athletics',
'Avalanche',
'Baby Cakes',
'Barnstormers',
'Barons',
'Bats',
'Bay Bears',
'Bay Sox',
'Beach Bums',
'Beach Cardinals',
'Bears',
'Bees',
'Bengals',
'Bills',
'Biscuits',
'Bisons',
'Black Bears',
'Blackhawks',
'Blackpool',
'Blue Bombers',
'Blue Crabs',
'Blue Jackets',
'Blue Jays',
'Blue Rocks',
'Blue Wahoos',
'Blue Claws',
'Bluefish',
'Blues',
'Boomers',
'Boulders',
'Bournemouth',
'Braves',
'Barves',
'Brentford',
'Brewers',
'Broncos',
'Browns',
'Bruins',
'Buccaneers',
'Bulls',
'Burnley',
'Bury',
'Canadians',
'Canaries',
'Canucks',
'Capitales',
'Capitals',
'Captains',
'Cardinals',
'Cavaliers',
'Celtics',
'Champions',
'Chargers',
'Chiefs',
'Chihuahuas',
'Bandits',
'Rascals',
'T-Bones',
'Wind',
'Clippers',
'College Spikes',
'Colts',
'Corn Belters',
'Cougars',
'County Miners',
'Cowboys',
'Coyotes',
'Crawdads',
'Crosscutters',
'Crushers',
'Cubs',
'Curve',
'Cyclones',
'Darlington',
'Dash',
'Devils',
'Diamondbacks',
'Diamonds',
'Dodgers',
'Dolphins',
'Doubledays',
'Dragons',
'Drillers',
'Drive',
'Ducks',
'Dust Devils',
'Eagles',
'Emeralds',
'Eskimos',
'Explorers',
'Express',
'Falcons',
'Falls Chukars',
'Fightin Phils',
'Fire Frogs',
'Fireflies',
'Fisher Cats',
'Flyers',
'Flying Squirrels',
'Forest',
'Freedom',
'Generals',
'Giants',
'Goats',
'Goldeyes',
'Grasshoppers',
'Green Jackets',
'Grizzlies',
'Hammerheads',
'Harriers',
'Hawks',
'Heat',
'Hillcats',
'Hooks',
'Hops',
'Hot Rods',
'Hurricanes',
'Indians',
'Intimidators',
'Invaders',
'Iron Birds',
'Iron Pigs',
'Island Ducks',
'Islanders',
'Isotopes',
'Jackals',
'Jaguars',
'Jet Hawks',
'Jets',
'Jumbo Shrimp',
'Keys',
'Knickerbockers',
'Knights',
'Laguna',
'Lake Monsters',
'Lakers',
'Land Skeeters',
'Legends',
'Lightning',
'Lions',
'Lookouts',
'Loons',
'Lugnuts',
'Lumber Kings',
'Maple Leafs',
'Marauders',
'Mariners',
'Marlins',
'Mavericks',
'Mets',
'Middlesbrough',
'Miners',
'Miracle',
'Missions',
'Muckdogs',
'Mud Hens',
'Mudcats',
'Mustangs',
'Nationals',
'Naturals',
'North End',
'Nuggets',
'Nuts',
'Orient',
'Orioles',
'Osprey',
'Otters',
'Owlz',
'Pacifics',
'Packers',
'Padres',
'Palace',
'Panthers',
'Park Rangers',
'Patriots',
'Pelicans',
'Penguins',
'Phillies',
'Pirates',
'Pistons',
'Ports',
'Power',
'Predators',
'Pupfish',
'Quakes',
'Raiders',
'Rail Cats',
'Rail Riders',
'Railroaders',
'Rainiers',
'Rams',
'Rangers',
'Rapids Kernels',
'Raptors',
'Ravens',
'Rawhide',
'Rays',
'Reading',
'Red Sox',
'Red Wings',
'Redbirds',
'Red Hawks',
'Reds',
'Redskins',
'Renegades',
'Revolution',
'River Cats',
'RiverDogs',
'Rochdale',
'Rock Hounds',
'Rockies',
'Rough Riders',
'Rovers',
'Royals',
'Rubber Ducks',
'Rumble Ponies',
'Sabres',
'Saguaros',
'Saints',
'Saltdogs',
'Scrappers',
'Sea Dogs',
'Sea Wolves',
'Senators',
'Sharks',
'Shorebirds',
'Shuckers',
'Sky Sox',
'Slammers',
'Smokies',
'Snappers',
'Sounds',
'Spinners',
'Spurs',
'Stampeders',
'Stanley',
'Stars',
'Steelers',
'Stockade',
'Stompers',
'Stone Crabs',
'Storm',
'Storm Chasers',
'Suns',
'SuperSonics',
'Surge',
'Threshers',
'Thunder',
'ThunderBolts',
'Tides',
'Tiger-Cats',
'Tigers',
'Timber Rattlers',
'Timberwolves',
'Tin Caps',
'Titans',
'Tortugas',
'Tourists',
'Trail Blazers',
'Train Robbers',
'Travelers',
'Triggers',
'Twins',
'United',
'Vale',
'Valley Cats',
'Victory',
'Vikings',
'Villa',
'Volcanoes',
'Voyagers',
'Wanderers',
'Wizards',
'Whiptails',
'White Sox',
'Whitecaps',
'Wild Things',
'Wingnuts',
'Wizards',
'Warriors',
'Wood Ducks',
'Wrexham',
'Yankees',
'Yardbirds'
]

mlbTeamNames =  ['Orioles', 'Red Sox', 'Yankees', 'Rays', 'Blue Jays',
                'White Sox', 'Indians', 'Tigers', 'Royals', 'Twins',
                'Astros', 'Angels', 'Athletics', 'Mariners', 'Rangers',
                'Braves', 'Marlins', 'Mets', 'Philies', 'Nationals',
                'Cubs', 'Reds', 'Brewers', 'Pirates', 'Cardinals',
                'Diamondbacks', 'Rockies', 'Padres', 'Dodgers', 'Giants']

mlbLocations = ['Baltimore', 'Boston', 'New York', 'Tampa Bay', 'Toronto',
                'Chicago', 'Cleveland', 'Detroit', 'Kansas City', 'Minnesota',
                'Houston', 'Los Angeles', 'Oakland', 'Seattle', 'Texas',
                'Atlanta', 'Miami', 'New York', 'Philadelphia', 'Washington',
                'Chicago', 'Cincinnati', 'Milwaukee', 'Pittsburg', 'St. Louis',
                'Arizona', 'Colorado', 'San Diego', 'Los Angeles', 'San Fransisco']

}
