import { Injectable } from '@angular/core';
import { Player  } from '../models/player';
import { Team, Roster, RosterSpot } from '../models/team';
import { GeneratePlayerService } from './generate-player.service';
import { TeamService } from '../backendServices/team/team.service';
import 'rxjs/add/operator/toPromise';

@Injectable()
export class GenerateTeamService {
    players = [];
    constructor(private generatePlayerSerivce: GeneratePlayerService,
                private teamService: TeamService) { }

    async generateTeam(leagueId: string) {
        var team = new Team(this.getTeamName(), this.getTeamLocation(), new Roster(new Array<RosterSpot>(), new Array<RosterSpot>()), leagueId);
        var id = leagueId + team.location.replace(/\s+/g, '') + team.name.replace(/\s+/g, '');
        team._id = id;
        for(let x = 0; x < 15; x++){
            var batter = await this.generatePlayerSerivce.generateBatter(leagueId, id, (new Date()).getFullYear());
            this.players.push(batter);
            if(x < 9){
              team.roster.batters.push(new RosterSpot(batter._id, this.positions[x], x+1, batter.tempId));
            } else {
              team.roster.batters.push(new RosterSpot(batter._id, null, null, null));
            }
        }

        for(let y = 0; y < 10; y++) {
            const pitcher = await this.generatePlayerSerivce.generatePitcher(leagueId, id, (new Date()).getFullYear());
            this.players.push(pitcher);
            if (y < 5) {
              team.roster.pitchers.push(new RosterSpot(pitcher._id, this.pitcherRoles[y], null, pitcher.tempId));
            } else {
              team.roster.pitchers.push(new RosterSpot(pitcher._id, null, null, pitcher.tempId));
            }
        }
        return await this.teamService.createTeam(team);
    }

    getTeamName(){
        return this.teamNames[Math.round(Math.random() * (this.teamNames.length - 1))];
    }

    getTeamLocation(){
        return this.teamLocations[Math.round(Math.random() * (this.teamLocations.length - 1))];
    }

     pitcherRoles = [
      'SP1',
      'SP2',
      'SP3',
      'SP4',
      'SP5'
    ]

     positions=[
      "C",
      "1B",
      "2B",
      "3B",
      "SS",
      "LF",
      "CF",
      "RF",
      "DH"
    ]

    teamLocations = [
 "Akron",
"Albuquerque",
"Alexandria",
"Amarillo",
"Anaheim",
"Anchorage",
"Arlington",
"Athens",
"Atlanta",
"Augusta",
"Aurora",
"Aurora",
"Austin",
"Bakersfield",
"Baltimore",
"Baton Rouge",
"Bellevue",
"Birmingham",
"Boise",
"Boston",
"Bridgeport",
"Brownsville",
"Buffalo",
"Cape Coral",
"Carrollton",
"Cary",
"Cedar Rapids",
"Chandler",
"Charleston",
"Charlotte",
"Chattanooga",
"Chesapeake",
"Chicago",
"Chula Vista",
"Cincinnati",
"Clarksville",
"Cleveland",
"Colorado Springs",
"Columbia",
"Columbus",
"Concord",
"Coral Springs",
"Corona",
"Corpus Christi",
"Dallas",
"Dayton",
"Denton",
"Denver",
"Des Moines",
"Detroit",
"Durham",
"El Paso",
"Elizabeth",
"Elk Grove",
"Escondido",
"Eugene",
"Fayetteville",
"Fontana",
"Fort Collins",
"Fort Lauderdale",
"Fort Wayne",
"Fort Worth",
"Fremont",
"Fresno",
"Frisco",
"Fullerton",
"Gainesville",
"Garden Grove",
"Garland",
"Gilbert",
"Glendale",
"Glendale",
"Grand Prairie",
"Grand Rapids",
"Greensboro",
"Hampton",
"Hartford",
"Hayward",
"Henderson",
"Hialeah",
"Hollywood",
"Honolulu",
"Houston",
"Huntington Beach",
"Huntsville",
"Indianapolis[11]",
"Irvine",
"Irving",
"Jackson",
"Jacksonville",
"Jersey City",
"Joliet",
"Kansas City",
"Kent",
"Killeen",
"Knoxville",
"Lafayette",
"Lakewood",
"Lancaster",
"Laredo",
"Las Vegas",
"Lexington",
"Lincoln",
"Little Rock",
"Long Beach",
"Los Angeles",
"Louisville",
"Lubbock",
"Macon",
"Madison",
"McAllen",
"McKinney",
"Memphis",
"Mesa",
"Mesquite",
"Miami",
"Midland",
"Milwaukee",
"Minneapolis",
"Miramar",
"Mobile",
"Modesto",
"Montgomery",
"Moreno Valley",
"Murfreesboro",
"Naperville",
"Nashville",
"New Haven",
"New Orleans",
"New York",
"Newark",
"Newport News",
"Norfolk",
"North Las Vegas",
"Oakland",
"Oceanside",
"Oklahoma City",
"Olathe",
"Omaha",
"Ontario",
"Orange",
"Orlando",
"Overland Park",
"Oxnard",
"Palmdale",
"Pasadena",
"Pasadena",
"Paterson",
"Pembroke Pines",
"Peoria",
"Philadelphia",
"Phoenix",
"Pittsburgh",
"Plano",
"Pomona",
"Port St. Lucie",
"Portland",
"Providence",
"Raleigh",
"Rancho Cucamonga",
"Reno",
"Richmond",
"Riverside",
"Rochester",
"Rockford",
"Roseville",
"Sacramento",
"Saint Paul",
"Salem",
"Salinas",
"Salt Lake City",
"San Antonio",
"San Bernardino",
"San Diego",
"San Francisco",
"San Jose",
"Santa Ana",
"Santa Clara",
"Santa Clarita",
"Santa Rosa",
"Savannah",
"Scottsdale",
"Seattle",
"Shreveport",
"Simi Valley",
"Sioux Falls",
"Spokane",
"Springfield",
"Springfield",
"St. Louis",
"St. Petersburg",
"Stamford",
"Sterling Heights",
"Stockton",
"Sunnyvale",
"Surprise",
"Syracuse",
"Tacoma",
"Tallahassee",
"Tampa",
"Tempe",
"Thornton",
"Thousand Oaks",
"Toledo",
"Topeka",
"Torrance",
"Tucson",
"Tulsa",
"Vancouver",
"Virginia Beach",
"Visalia",
"Waco",
"Warren",
"Washington",
"West Valley City",
"Wichita",
"Winston-Salem",
"Worcester",
"Yonkers"
]

teamNames = [
"49ers",
"51s",
"66ers",
"76ers",
"Aces",
"Admirals",
"Aigles",
"AirHogs",
"Alouettes",
"Altrincham",
"Amberjacks",
"Angels",
"AquaSox",
"Argonauts",
"Argyle",
"Arsenal",
"Astros",
"Athletics",
"Avalanche",
"Baby Cakes",
"Barnet",
"Barnsley",
"Barnstormers",
"Barons",
"Bats",
"BayBears",
"Baysox",
"Beach Bums",
"Beach Cardinals",
"Bears",
"Bees",
"Bengals",
"Bills",
"Biscuits",
"Bisons",
"Black Bears",
"Blackhawks",
"Blackpool",
"Blue Bombers",
"Blue Crabs",
"Blue Jackets",
"Blue Jays",
"Blue Rocks",
"Blue Wahoos",
"BlueClaws",
"Bluefish",
"Blues",
"Boomers",
"Boulders",
"Bournemouth",
"Braves",
"Braves",
"Braves",
"Brentford",
"Brewers",
"Brewers",
"Broncos",
"Browns",
"Bruins",
"Buccaneers",
"Bulls",
"Bulls",
"Burnley",
"Bury",
"Canadians",
"Canaries",
"Canucks",
"Capitales",
"Capitals",
"Captains",
"Cardinals",
"Cavaliers",
"Celtics",
"Champions",
"Chargers",
"Chelsea",
"Chesterfield",
"Chiefs",
"Chihuahuas",
"Cities River Bandits",
"City Rascals",
"City T-Bones",
"City Wind",
"Clippers",
"College Spikes",
"Colts",
"CornBelters",
"Cougars",
"County Miners",
"Cowboys",
"Coyotes",
"Crawdads",
"Crosscutters",
"Crushers",
"Cubs",
"Curve",
"Cyclones",
"Darlington",
"Dash",
"de Yucatán",
"Devils",
"Diamondbacks",
"Diamonds",
"Diamonds",
"Dodgers",
"Dolphins",
"Doubledays",
"Dragons",
"Drillers",
"Drive",
"Ducks",
"Dust Devils",
"Eagles",
"Emeralds",
"Eskimos",
"Everton",
"Explorers",
"Explorers",
"Express",
"Falcons",
"Falls Chukars",
"Fightin Phils",
"Fire Frogs",
"Fireflies",
"Fisher Cats",
"Flyers",
"Flying Squirrels",
"Forest",
"Freedom",
"Fulham",
"Generals",
"Giants",
"Gillingham",
"Goats",
"Goldeyes",
"Grasshoppers",
"GreenJackets",
"Grizzlies",
"Grizzlies",
"Hammerheads",
"Harriers",
"Hawks",
"Hawks",
"Heat",
"Hillcats",
"Hooks",
"Hops",
"Hot Rods",
"Hotspur",
"Hurricanes",
"Indians",
"Intimidators",
"Invaders",
"IronBirds",
"IronPigs",
"Island Ducks",
"Islanders",
"Isotopes",
"Jackals",
"Jaguars",
"JetHawks",
"Jets",
"Jumbo Shrimp",
"Keys",
"Knickerbockers",
"Knights",
"Laguna",
"Lake Monsters",
"Lakers",
"Land Skeeters",
"Legends",
"Lightning",
"Lions",
"Lions",
"Liverpool",
"Liverpool",
"Lookouts",
"Loons",
"Lugnuts",
"LumberKings",
"Maple Leafs",
"Marauders",
"Mariners",
"Marlins",
"Mavericks",
"Mets",
"Middlesbrough",
"Millwall",
"Miners",
"Miracle",
"Missions",
"Morecambe",
"Muckdogs",
"Mud Hens",
"Mudcats",
"Mustangs",
"Nationals",
"Naturals",
"North End",
"Nuggets",
"Nuts",
"Orient",
"Orioles",
"Osprey",
"Otters",
"Owlz",
"Pacifics",
"Packers",
"Padres",
"Palace",
"Panthers",
"Park Rangers",
"Patriots",
"Pelicans",
"Penguins",
"Phillies",
"Pirates",
"Pistons",
"Ports",
"Portsmouth",
"Power",
"Predators",
"Pupfish",
"Quakes",
"Raiders",
"RailCats",
"RailRiders",
"Railroaders",
"Rainiers",
"Rams",
"Rangers",
"Rapids Kernels",
"Raptors",
"Ravens",
"Rawhide",
"Rays",
"Reading",
"Red Sox",
"Red Wings",
"Redbirds",
"RedHawks",
"Reds",
"Redskins",
"Renegades",
"Revolution",
"River Cats",
"RiverDogs",
"Rochdale",
"RockHounds",
"Rockies",
"RoughRiders",
"Rovers",
"Royals",
"RubberDucks",
"Rumble Ponies",
"Sabres",
"Saguaros",
"Saints",
"Saints",
"Saltdogs",
"Scrappers",
"Sea Dogs",
"SeaWolves",
"Senators",
"Sharks",
"Shorebirds",
"Shuckers",
"Sky Sox",
"Slammers",
"Smokies",
"Snappers",
"Sounds",
"Southampton",
"Southend",
"Southport",
"Spinners",
"Spurs",
"Stampeders",
"Stanley",
"Stars",
"State Warriors",
"Steelers",
"Stockade",
"Stompers",
"Stone Crabs",
"Storm",
"Storm Chasers",
"Sunderland",
"Suns",
"SuperSonics",
"Surge",
"Tamworth",
"Threshers",
"Thunder",
"Thunder",
"ThunderBolts",
"Tides",
"Tiger-Cats",
"Tigers",
"Timber Rattlers",
"Timberwolves",
"TinCaps",
"Titans",
"Tortugas",
"Tourists",
"Trail Blazers",
"Train Robbers",
"Travelers",
"Triggers",
"Twins",
"United",
"Vale",
"ValleyCats",
"Victoria",
"Vikings",
"Villa",
"Volcanoes",
"Voyagers",
"Walsall",
"Wanderers",
"Wizards",
"Watford",
"Weymouth",
"Whiptails",
"White Sox",
"Whitecaps",
"Wild Things",
"Wingnuts",
"Wizards",
"Woking",
"Wood Ducks",
"Wrexham",
"Yankees",
"Yardbirds"
]

}
